SECTION_HEADERS = [
    r"^En gemensam grund för alla statsanställda",
    r"^Regeringsformen utgör grunden",
    r"^Grunderna för en god förvaltning",
    r"^Demokrati",
    r"^Regeringsformen ger oss utgångspunkten",
    r"^Du som arbetar i förvaltningen är en del av den demokratiska styrkedjan",
    r"^Det ingår i uppdraget att upprätthålla demokratiska värden",
    r"^Det kan vara svårt att bedöma vad som är demokratiska värderingar",
    r"^Som statligt anställd måste du respektera vissa värden, men du har yttrandefrihet",
    r"^Legalitet",
    r"^Myndigheterna måste ha stöd i reglerna för verksamheten",
    r"^Vissa saker måste meddelas i lag",
    r"^Du måste känna till de regler som verksamheten berörs av",
    r"^Du måste kunna principerna för tolkning",
    r"^Objektivitet",
    r"^Du ska vara saklig och opartisk i all verksamhet",
    r"^Kravet på saklighet hänger samman med legalitetsprincipen",
    r"^Opartiskheten handlar ytterst om hur processen uppfattas utifrån",
    r"^Krav på saklighet och opartiskhet återkommer i fler regler",
    r"^Statlig anställning ska ske på saklig grund",
    r"^Bisysslor kan vara otillåtna om de riskerar att skada förtroendet",
    r"^Jäv handlar också om hur det ser ut utifrån",
    r"^Ansvaret är både ditt och myndighetens",
    r"^Korruption och oegentligheter – höjden av partiskt och osakligt",
    r"^Fri åsiktsbildning",
    r"^Fri- och rättigheterna är omfattande, men det finns gränser",
    r"^Även som statsanställd har du fri- och rättigheter",
    r"^Myndigheterna ska vara öppna och transparenta och det ska gå att följa vägen till beslut",
    r"^Meddelarskyddet ger offentliganställda en särställning",
    r"^Visselblåsning",
    r"^Respekt",
    r"^Mål för all samhällelig verksamhet",
    r"^Ickediskriminering",
    r"^Personlig integritet",
    r"^Effektivitet och service",
    r"^Effektivitet vägs mot rättssäkerhet och andra värden",
    r"^Alla myndigheter är skyldiga att ge service, vara tillgängliga och samverka",
    r"^Myndigheterna arbetar i huvudsak på svenska",
    r"^Lagar och principer av vikt utanför värdegrunden",
    r"^Grunderna för god förvaltning",
    r"^Proportionalitet – en europeisk princip",
    r"^Subsidiaritetsprincipen",
    r"^Andra EU-rättsliga principer",
    r"^Att skapa förutsättningar för en god förvaltning",
    r"^Det krävs ett aktivt arbete",
    r"^Värdegrunden behöver diskuteras och konkretiseras",
    r"^Vill du veta mer\?",
    r"^Handböcker:",
    r"^Rapporter:",
    r"^Rättsfall och myndighetspraxis",
    r"^Högsta förvaltningsdomstolen",
    r"^Arbetsdomstolen",
    r"^Hovrätt och Kammarrätt",
    r"^Justitieombudsmannen",
    r"^Justitiekanslern",
    r"^Diskrimineringsombudsmannen",
    r"^Den statliga värdegrunden – gemensamma principer för en god förvaltning", 
    r"^Diskutera den statliga värdegrunden",
    r"^Övningar",
    r"^Övning om den statliga värdegrunden",
    r"^Gäller den statliga värdegrunden även på fritiden?",
    r"^Diskussionsfrågor med läsanvisning",
    r"^Dialogträning med dilemman för både chefer och medarbetare",
    r"^Så kan man arbeta vidare med egna dilemman",
]
