# Generated by Django 5.0.6 on 2026-02-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_userlongtermmemory'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
